const areaData : string[] = [
    "abia",
    "adamawa",
    "akwa ibom",
    "anambra",
    "bauchi",
    "bayelsa",
    "benue",
    "borno",
    "cross river",
    "delta",
    "ebonyi",
    "edo",
    "enugu",
    "gombe",
    "imo",
    "jigawa",
    "kaduna",
    "kano",
    "katsina",
    "kebbi",
    "kogi",
    "kwara",
    "lagos",
    "maiduguri",
    "nasarawa",
    "niger",
    "ogun",
    "ondo",
    "osun",
    "oyo",
    "plateau",
    "rivers",
    "sokoto",
    "taraba",
    "zamfara",
    "federal capital teritory",
    "ekiti",
    "Ghana",
    "jalingo",
    "greater accra region",
    "west akim municipal",
    "nanumba north",
    "bolgatanga municipal",
    "cape coast metropolitan",
    "garu-tempane district",
    "ashanti region",
    "sekondi-taoradi metropolitan",
    "tema metropolitan",
    "tarkwa-nsuaem municipal",
    "sissala east district",
    "sunyani municipal district",
    "ho municipal district",
    "accra metropolitan"
]


export const domesticDepartureDestinationAreaData: { value: string, label: string }[] = areaData.map(val => {
    return {
        value: val,
        label: (val ?? "").toUpperCase()
    }   
})
